language: node_js
node_js:
  - 0.8
before_install:
  - npm update -g npm
  - npm install -g grunt-cli
  - wget --no-check-certificate https://foundationdb.com/downloads/token/3ffff3ae-0122-45c5-aea3-4be53eaa838b/key-value-store/3.0.6/foundationdb-clients_3.0.6-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_3.0.6-1_amd64.deb
